/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.toronto.cs.jcudd;


public class CIntPtr {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CIntPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      JMVLCuddJNI.delete_CIntPtr(swigCPtr);
    }
    swigCPtr = 0;
  }

  protected static long getCPtr(CIntPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public CIntPtr() {
    this(JMVLCuddJNI.new_CIntPtr(), true);
  }

  public void assign(int value) {
    JMVLCuddJNI.CIntPtr_assign(swigCPtr, value);
  }

  public int value() {
    return JMVLCuddJNI.CIntPtr_value(swigCPtr);
  }

  public SWIGTYPE_p_int cast() {
    long cPtr = JMVLCuddJNI.CIntPtr_cast(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static CIntPtr frompointer(SWIGTYPE_p_int t) {
    long cPtr = JMVLCuddJNI.CIntPtr_frompointer(SWIGTYPE_p_int.getCPtr(t));
    return (cPtr == 0) ? null : new CIntPtr(cPtr, false);
  }

}
