/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.toronto.cs.jcudd;


public class CIntArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CIntArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected CIntArray() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      JMVLCuddJNI.delete_CIntArray(swigCPtr);
    }
    swigCPtr = 0;
  }

  protected static long getCPtr(CIntArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public CIntArray(int nelements) {
    this(JMVLCuddJNI.new_CIntArray(nelements), true);
  }

  public int getitem(int index) {
    return JMVLCuddJNI.CIntArray_getitem(swigCPtr, index);
  }

  public void setitem(int index, int value) {
    JMVLCuddJNI.CIntArray_setitem(swigCPtr, index, value);
  }

  public SWIGTYPE_p_int cast() {
    long cPtr = JMVLCuddJNI.CIntArray_cast(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static CIntArray frompointer(SWIGTYPE_p_int t) {
    long cPtr = JMVLCuddJNI.CIntArray_frompointer(SWIGTYPE_p_int.getCPtr(t));
    return (cPtr == 0) ? null : new CIntArray(cPtr, false);
  }

}
