/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.toronto.cs.jcudd;


public class CuddCube {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CuddCube(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      JMVLCuddJNI.delete_CuddCube(swigCPtr);
    }
    swigCPtr = 0;
  }

  protected static long getCPtr(CuddCube obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void setCube(SWIGTYPE_p_int cube) {
    JMVLCuddJNI.set_CuddCube_cube(swigCPtr, SWIGTYPE_p_int.getCPtr(cube));
  }

  public SWIGTYPE_p_int getCube() {
    long cPtr = JMVLCuddJNI.get_CuddCube_cube(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setValue(int value) {
    JMVLCuddJNI.set_CuddCube_value(swigCPtr, value);
  }

  public int getValue() {
    return JMVLCuddJNI.get_CuddCube_value(swigCPtr);
  }

  public CuddCube() {
    this(JMVLCuddJNI.new_CuddCube(), true);
  }

}
