package edu.toronto.cs.jcudd;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface JMVLCuddConstants {
  // enums and constants
  public final static int CUDD_REORDER_SAME = JMVLCuddJNI.get_CUDD_REORDER_SAME();
  public final static int CUDD_REORDER_NONE = JMVLCuddJNI.get_CUDD_REORDER_NONE();
  public final static int CUDD_REORDER_RANDOM = JMVLCuddJNI.get_CUDD_REORDER_RANDOM();
  public final static int CUDD_REORDER_RANDOM_PIVOT = JMVLCuddJNI.get_CUDD_REORDER_RANDOM_PIVOT();
  public final static int CUDD_REORDER_SIFT = JMVLCuddJNI.get_CUDD_REORDER_SIFT();
  public final static int CUDD_REORDER_SIFT_CONVERGE = JMVLCuddJNI.get_CUDD_REORDER_SIFT_CONVERGE();
  public final static int CUDD_REORDER_SYMM_SIFT = JMVLCuddJNI.get_CUDD_REORDER_SYMM_SIFT();
  public final static int CUDD_REORDER_SYMM_SIFT_CONV = JMVLCuddJNI.get_CUDD_REORDER_SYMM_SIFT_CONV();
  public final static int CUDD_REORDER_WINDOW2 = JMVLCuddJNI.get_CUDD_REORDER_WINDOW2();
  public final static int CUDD_REORDER_WINDOW3 = JMVLCuddJNI.get_CUDD_REORDER_WINDOW3();
  public final static int CUDD_REORDER_WINDOW4 = JMVLCuddJNI.get_CUDD_REORDER_WINDOW4();
  public final static int CUDD_REORDER_WINDOW2_CONV = JMVLCuddJNI.get_CUDD_REORDER_WINDOW2_CONV();
  public final static int CUDD_REORDER_WINDOW3_CONV = JMVLCuddJNI.get_CUDD_REORDER_WINDOW3_CONV();
  public final static int CUDD_REORDER_WINDOW4_CONV = JMVLCuddJNI.get_CUDD_REORDER_WINDOW4_CONV();
  public final static int CUDD_REORDER_GROUP_SIFT = JMVLCuddJNI.get_CUDD_REORDER_GROUP_SIFT();
  public final static int CUDD_REORDER_GROUP_SIFT_CONV = JMVLCuddJNI.get_CUDD_REORDER_GROUP_SIFT_CONV();
  public final static int CUDD_REORDER_ANNEALING = JMVLCuddJNI.get_CUDD_REORDER_ANNEALING();
  public final static int CUDD_REORDER_GENETIC = JMVLCuddJNI.get_CUDD_REORDER_GENETIC();
  public final static int CUDD_REORDER_LINEAR = JMVLCuddJNI.get_CUDD_REORDER_LINEAR();
  public final static int CUDD_REORDER_LINEAR_CONVERGE = JMVLCuddJNI.get_CUDD_REORDER_LINEAR_CONVERGE();
  public final static int CUDD_REORDER_EXACT = JMVLCuddJNI.get_CUDD_REORDER_EXACT();
}
