package edu.toronto.cs.jcudd;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class JMVLCuddJNI {
  public final static native long new_CIntArray(int jarg1);
  public final static native void delete_CIntArray(long jarg1);
  public final static native int CIntArray_getitem(long jarg1, int jarg2);
  public final static native void CIntArray_setitem(long jarg1, int jarg2, int jarg3);
  public final static native long CIntArray_cast(long jarg1);
  public final static native long CIntArray_frompointer(long jarg1);
  public final static native long new_CIntPtr();
  public final static native void delete_CIntPtr(long jarg1);
  public final static native void CIntPtr_assign(long jarg1, int jarg2);
  public final static native int CIntPtr_value(long jarg1);
  public final static native long CIntPtr_cast(long jarg1);
  public final static native long CIntPtr_frompointer(long jarg1);
  public final static native void set_CuddCube_cube(long jarg1, long jarg2);
  public final static native long get_CuddCube_cube(long jarg1);
  public final static native void set_CuddCube_value(long jarg1, int jarg2);
  public final static native int get_CuddCube_value(long jarg1);
  public final static native long new_CuddCube();
  public final static native void delete_CuddCube(long jarg1);
  public final static native int get_CUDD_REORDER_SAME();
  public final static native int get_CUDD_REORDER_NONE();
  public final static native int get_CUDD_REORDER_RANDOM();
  public final static native int get_CUDD_REORDER_RANDOM_PIVOT();
  public final static native int get_CUDD_REORDER_SIFT();
  public final static native int get_CUDD_REORDER_SIFT_CONVERGE();
  public final static native int get_CUDD_REORDER_SYMM_SIFT();
  public final static native int get_CUDD_REORDER_SYMM_SIFT_CONV();
  public final static native int get_CUDD_REORDER_WINDOW2();
  public final static native int get_CUDD_REORDER_WINDOW3();
  public final static native int get_CUDD_REORDER_WINDOW4();
  public final static native int get_CUDD_REORDER_WINDOW2_CONV();
  public final static native int get_CUDD_REORDER_WINDOW3_CONV();
  public final static native int get_CUDD_REORDER_WINDOW4_CONV();
  public final static native int get_CUDD_REORDER_GROUP_SIFT();
  public final static native int get_CUDD_REORDER_GROUP_SIFT_CONV();
  public final static native int get_CUDD_REORDER_ANNEALING();
  public final static native int get_CUDD_REORDER_GENETIC();
  public final static native int get_CUDD_REORDER_LINEAR();
  public final static native int get_CUDD_REORDER_LINEAR_CONVERGE();
  public final static native int get_CUDD_REORDER_EXACT();
  public final static native int isCube(int jarg1, int jarg2);
  public final static native void Cudd_AutodynEnable(int jarg1, int jarg2);
  public final static native void Cudd_AutodynDisable(int jarg1);
  public final static native int jmvlCudd_Init(int jarg1, Object jarg2, int jarg3, int jarg4, int jarg5, int jarg6);
  public final static native void jmvlCudd_Quit(int jarg1);
  public final static native void Cudd_RecursiveDeref(int jarg1, int jarg2);
  public final static native int Cudd_PrintMinterm(int jarg1, int jarg2);
  public final static native int Cudd_CheckZeroRef(int jarg1);
  public final static native int cuddV(int jarg1);
  public final static native int Cudd_IsConstant(int jarg1);
  public final static native int cuddGarbageCollect(int jarg1, int jarg2);
  public final static native void Cudd_Ref(int jarg1);
  public final static native int Cudd_DagSize(int jarg1);
  public final static native int Cudd_FirstCube(int jarg1, int jarg2, CuddCube jarg3);
  public final static native int Cudd_NextCube(int jarg1, CuddCube jarg2);
  public final static native int Cudd_GenFree(int jarg1);
  public final static native int ddSize(int jarg1);
  public final static native int Cudd_ReadOne(int jarg1);
  public final static native int Cudd_ReadLogicZero(int jarg1);
  public final static native int Cudd_Not(int jarg1);
  public final static native int Cudd_bddAnd(int jarg1, int jarg2, int jarg3);
  public final static native int Cudd_bddOr(int jarg1, int jarg2, int jarg3);
  public final static native int Cudd_bddIte(int jarg1, int jarg2, int jarg3, int jarg4);
  public final static native int Cudd_bddUnivAbstract(int jarg1, int jarg2, int jarg3);
  public final static native int Cudd_bddExistAbstract(int jarg1, int jarg2, int jarg3);
  public final static native int Cudd_bddNewVar(int jarg1);
  public final static native int Cudd_bddIthVar(int jarg1, int jarg2);
  public final static native int Cudd_bddXor(int jarg1, int jarg2, int jarg3);
  public final static native int Cudd_bddPermute(int jarg1, int jarg2, long jarg3);
  public final static native int Cudd_bddAndAbstract(int jarg1, int jarg2, int jarg3, int jarg4);
  public final static native int Cudd_addNewVar(int jarg1);
  public final static native int Cudd_addIthVar(int jarg1, int jarg2);
  public final static native int Cudd_addConst(int jarg1, int jarg2);
  public final static native int Cudd_addIte(int jarg1, int jarg2, int jarg3, int jarg4);
  public final static native int Cudd_addPermute(int jarg1, int jarg2, long jarg3);
  public final static native int Cudd_Cofactor(int jarg1, int jarg2, int jarg3);
  public final static native int jmvlCudd_Not(int jarg1, int jarg2);
  public final static native int jmvlCudd_And(int jarg1, int jarg2, int jarg3);
  public final static native int jmvlCudd_Or(int jarg1, int jarg2, int jarg3);
  public final static native int jmvlCudd_Eq(int jarg1, int jarg2, int jarg3);
  public final static native int jmvlCudd_Above(int jarg1, int jarg2, int jarg3);
  public final static native int jmvlCudd_Below(int jarg1, int jarg2, int jarg3);
  public final static native int jmvlCudd_infoNot(int jarg1, int jarg2);
  public final static native int jmvlCudd_infoMeet(int jarg1, int jarg2, int jarg3);
  public final static native int jmvlCudd_infoJoin(int jarg1, int jarg2, int jarg3);
  public final static native int jmvlCudd_infoAbove(int jarg1, int jarg2, int jarg3);
  public final static native int jmvlCudd_infoBelow(int jarg1, int jarg2, int jarg3);
  public final static native int mvlCudd_ExistAbstract(int jarg1, int jarg2, int jarg3);
  public final static native int mvlCudd_UnivAbstract(int jarg1, int jarg2, int jarg3);
  public final static native int mvlCudd_ExistMeetAbstract(int jarg1, int jarg2, int jarg3, int jarg4);
  public final static native int mvlCudd_Support(int jarg1, int jarg2);
  public final static native int mvlCudd_CubeDiff(int jarg1, int jarg2, int jarg3);
  public final static native int mvlCudd_NextMinterm(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5);
  public final static native int mvlCudd_bddNextMinterm(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5);
  public final static native int mvlCudd_MintermIterator(int jarg1, int jarg2);
  public final static native int mvlCudd_HasNextMinterm(int jarg1, int jarg2);
}
